#成教学员
CStudent:
  mobile: None
  id_card: None
  grade: None
  unvs_name: None
  pfsn_name: None
  schoolarship_name: None
  recruit_type: None
  ta_name: None
  learn_id: None
  std_id: None

#国开学员
GStudent:
  mobile: None
  id_card: None
  grade: None
  unvs_name: None
  pfsn_name: None
  schoolarship_name: None
  recruit_type: None
  ta_name: None
  learn_id: None
  std_id: None